spring:
  datasource:
    ###可读数据源
    select:
      jdbc-url: jdbc:mysql://192.168.122.145:8066/qa?useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: user
      password: 123456
    ####可写数据源  
    update:
      jdbc-url: jdbc:mysql://192.168.122.145:8066/qa?useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: user
      password: 123456
    type: com.alibaba.druid.pool.DruidDataSource